name: Production Release

on:
  release:
    types: [published]

jobs:
  netlify-deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    environment:
      name: production
      url: ${{ steps.deploy-netlify.outputs.NETLIFY_LIVE_URL }}
    steps:
    # checkout code
    - uses: actions/checkout@v3
    # cache
    - uses: actions/cache@v3
      with:
        path: |
          **/node_modules
          ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    # cli message
    - run: echo "Releasing ${GITHUB_REF:10} to netlify production"
    # install node and dependencies
    - uses: actions/setup-node@v3
    - run: npm install
    # build and deploy to netlify
    - name: Deploy to netlify
      run: netlify deploy --build --prod --message "Deploy triggered by Github Release"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
